### PR TITLE
Implemented threaded downloading

### PR DESCRIPTION
**Pull request by pudelkoM**
# [YOLO](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) :fast_forward:

### CODE REVIEW

**Comment by irgendwie** [comment]
Would you mind to not reformatting the complete file? :smile:

**Comment by pudelkoM** [comment]
Yes

**Comment by irgendwie** [comment]
"Tabs should be used solely to remain consistent with code that is already indented with tabs." :coffee:

**Comment by pudelkoM** [comment]
Better now?

**Pull request merged**
